version: "3.3"

services:
  qix-engine:
    image: qlikcore/engine:12.401.0
    restart: always
    command: |
      -S AcceptEULA=${ACCEPT_EULA}
      -S StandardReload=0
      -S DocumentDirectory=/data
    ports:
      - 39076:9076
    volumes:
      - ./data:/data
